name: Build and deploy ASP.Net Core app to Azure Web App - barbershop-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        # Updated to match your actual folder name
        run: dotnet build BarberShopBookingSystem/BarberShopBookingSystem.csproj --configuration Release

      - name: dotnet publish
        # Tells dotnet exactly which project to publish
        run: dotnet publish BarberShopBookingSystem/BarberShopBookingSystem.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F442F26824D4B148CA9A4716E0A40B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C8E58A8E09146EC8E05DEDCD299BF3C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_938ADE99348147659D5532B5AC0A07BD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'barbershop-api'
          slot-name: 'Production'
          package: ./publish
